#include "nvram_utils.h"

extern "C"
{
#include "nrf.h"
}

namespace zigbee_utils
{
    extern const unsigned int kBuildTimestamp;
}

static void wait_for_ready()
{
    while (NRF_NVMC->READY != NVMC_READY_READY_Ready)
    {
    };
}

/**
 * @brief This function tries to detect if a new Arduino sketch has been flashed.
 * Since it seems that at the moment the sketch info is not provided by Arduino we try to use the compilation timestamp generated by the header ArduinoZigbee.h included in the *.ino file.
 *
 * @return true or false
 */
bool isSketchChanged()
{
    bool changed = false;
    if (NRF_UICR->CUSTOMER[0] != zigbee_utils::kBuildTimestamp)
    {
        if (NRF_UICR->CUSTOMER[0] != 0xFFFFFFFF)
        {
            /* Erase the memory block. */
            wait_for_ready();
            NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Een << NVMC_CONFIG_WEN_Pos;
            wait_for_ready();
            NRF_NVMC->ERASEUICR = NVMC_ERASEUICR_ERASEUICR_Erase;
        }
        /* Write the updated timestamp. */
        wait_for_ready();
        NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Wen << NVMC_CONFIG_WEN_Pos;
        wait_for_ready();
        NRF_UICR->CUSTOMER[0] = zigbee_utils::kBuildTimestamp;
        wait_for_ready();
        NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos;
        wait_for_ready();
        changed = true;
    }
    return changed;
}